# Generated by Django 3.1.2 on 2020-11-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201011_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='latitud',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='longitud',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
    ]
