# Generated by Django 3.1.2 on 2020-11-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201111_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
