# Generated by Django 3.1.3 on 2020-11-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201117_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at'),
        ),
    ]
