# Generated by Django 3.1.2 on 2020-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
