# Generated by Django 3.1.3 on 2020-11-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201117_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reputation',
            field=models.FloatField(default=5.0, help_text="User's reputation based on the rides taken and offered."),
        ),
    ]
